version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - revive
    
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: false
      
    revive:
      confidence: 0.8
      
  exclusions:
    presets: []
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
    
issues:
  max-issues-per-linter: 0
  max-same-issues: 0